%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(addFriendReq_pb).
-define(addFriendReq_pb, true).

-define(addFriendReq_pb_gpb_version, "3.26.4").

-ifndef('ADDFRIENDREQ_PB_H').
-define('ADDFRIENDREQ_PB_H', true).
-record(addFriendReq,
        {toUser                 :: binary() | iolist(), % = 1
         sendFrom               :: binary() | iolist() % = 2
        }).
-endif.

-endif.
