%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(chat_pb).
-define(chat_pb, true).

-define(chat_pb_gpb_version, "3.26.4").

-ifndef('SENDMESSAGEREQUEST_PB_H').
-define('SENDMESSAGEREQUEST_PB_H', true).
-record('SendMessageRequest',
        {access_token           :: binary() | iolist(), % = 1
         from                   :: binary() | iolist(), % = 2
         to                     :: binary() | iolist(), % = 3
         text                   :: binary() | iolist(), % = 4
         topic                  :: binary() | iolist() % = 5
        }).
-endif.

-ifndef('SENDMESSAGERESPONSE_PB_H').
-define('SENDMESSAGERESPONSE_PB_H', true).
-record('SendMessageResponse',
        {err_code               :: integer(),       % = 1, 32 bits
         err_msg                :: binary() | iolist(), % = 2
         from                   :: binary() | iolist(), % = 3
         text                   :: binary() | iolist(), % = 4
         topic                  :: binary() | iolist() % = 5
        }).
-endif.

-endif.
