%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(getFriendListRsp_pb).
-define(getFriendListRsp_pb, true).

-define(getFriendListRsp_pb_gpb_version, "3.26.4").

-ifndef('CHATFRIEND_PB_H').
-define('CHATFRIEND_PB_H', true).
-record(chatFriend,
        {toUser                 :: binary() | iolist(), % = 1
         sendFrom               :: binary() | iolist(), % = 2
         reqStatus              :: integer(),       % = 3, 32 bits
         nickName               :: binary() | iolist(), % = 4
         acceptDate             :: binary() | iolist() | undefined, % = 5
         createDate             :: binary() | iolist() | undefined % = 6
        }).
-endif.

-ifndef('FRIENDLISTRSP_PB_H').
-define('FRIENDLISTRSP_PB_H', true).
-record(friendListRsp,
        {friends = []           :: [#chatFriend{}]  % = 1
        }).
-endif.

-endif.
