%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(loginReq_pb).
-define(loginReq_pb, true).

-define(loginReq_pb_gpb_version, "3.26.4").

-ifndef('LOGINREQ_PB_H').
-define('LOGINREQ_PB_H', true).
-record(loginReq,
        {account                :: binary() | iolist(), % = 1
         password               :: binary() | iolist() % = 2
        }).
-endif.

-endif.
