%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(messageRsp_pb).
-define(messageRsp_pb, true).

-define(messageRsp_pb_gpb_version, "3.26.4").

-ifndef('MESSAGEBUFFER_PB_H').
-define('MESSAGEBUFFER_PB_H', true).
-record(messageBuffer,
        {id                     :: integer(),       % = 1, 32 bits
         content                :: binary() | iolist(), % = 2
         groupId                :: integer() | undefined, % = 3, 32 bits
         toUser                 :: binary() | iolist(), % = 4
         sendFrom               :: binary() | iolist(), % = 5
         status                 :: integer(),       % = 6, 32 bits
         recDate                :: binary() | iolist() | undefined, % = 7
         sendDate               :: binary() | iolist() | undefined % = 8
        }).
-endif.

-ifndef('CHATMESSAGELISTRSP_PB_H').
-define('CHATMESSAGELISTRSP_PB_H', true).
-record(chatMessageListRsp,
        {messages = []          :: [#messageBuffer{}] % = 1
        }).
-endif.

-endif.
