%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(newGroupReq_pb).
-define(newGroupReq_pb, true).

-define(newGroupReq_pb_gpb_version, "3.26.4").

-ifndef('NEWGROUPREQ_PB_H').
-define('NEWGROUPREQ_PB_H', true).
-record(newGroupReq,
        {groupName              :: binary() | iolist(), % = 1
         groupLevel             :: integer() | undefined, % = 2, 32 bits
         note                   :: binary() | iolist() | undefined, % = 3
         remarks                :: binary() | iolist() | undefined, % = 4
         ownUser                :: binary() | iolist(), % = 5
         status                 :: integer(),       % = 6, 32 bits
         createDate             :: binary() | iolist() | undefined % = 7
        }).
-endif.

-endif.
