%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4
-module(newGroupReq_pb).

-export([encode_msg/1, encode_msg/2]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3]).
-export([verify_msg/1, verify_msg/2]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("newGroupReq_pb.hrl").
-include("gpb.hrl").

%% enumerated types

-export_type([]).

%% message types
-type newGroupReq() :: #newGroupReq{}.
-export_type(['newGroupReq'/0]).


-spec encode_msg(_) -> binary().
encode_msg(Msg) -> encode_msg(Msg, []).


-spec encode_msg(_, list()) -> binary().
encode_msg(Msg, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #newGroupReq{} -> e_msg_newGroupReq(Msg, TrUserData)
    end.



e_msg_newGroupReq(Msg, TrUserData) ->
    e_msg_newGroupReq(Msg, <<>>, TrUserData).


e_msg_newGroupReq(#newGroupReq{groupName = F1,
			       groupLevel = F2, note = F3, remarks = F4,
			       ownUser = F5, status = F6, createDate = F7},
		  Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_string(TrF1, <<Bin/binary, 10>>)
	 end,
    B2 = if F2 == undefined -> B1;
	    true ->
		begin
		  TrF2 = id(F2, TrUserData),
		  e_type_int32(TrF2, <<B1/binary, 16>>)
		end
	 end,
    B3 = if F3 == undefined -> B2;
	    true ->
		begin
		  TrF3 = id(F3, TrUserData),
		  e_type_string(TrF3, <<B2/binary, 26>>)
		end
	 end,
    B4 = if F4 == undefined -> B3;
	    true ->
		begin
		  TrF4 = id(F4, TrUserData),
		  e_type_string(TrF4, <<B3/binary, 34>>)
		end
	 end,
    B5 = begin
	   TrF5 = id(F5, TrUserData),
	   e_type_string(TrF5, <<B4/binary, 42>>)
	 end,
    B6 = begin
	   TrF6 = id(F6, TrUserData),
	   e_type_int32(TrF6, <<B5/binary, 48>>)
	 end,
    if F7 == undefined -> B6;
       true ->
	   begin
	     TrF7 = id(F7, TrUserData),
	     e_type_string(TrF7, <<B6/binary, 58>>)
	   end
    end.



e_type_int32(Value, Bin)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int32(Value, Bin) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

e_type_string(S, Bin) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).



decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      newGroupReq -> d_msg_newGroupReq(Bin, TrUserData)
    end.



d_msg_newGroupReq(Bin, TrUserData) ->
    dfp_read_field_def_newGroupReq(Bin, 0, 0,
				   id(undefined, TrUserData),
				   id(undefined, TrUserData),
				   id(undefined, TrUserData),
				   id(undefined, TrUserData),
				   id(undefined, TrUserData),
				   id(undefined, TrUserData),
				   id(undefined, TrUserData), TrUserData).

dfp_read_field_def_newGroupReq(<<10, Rest/binary>>, Z1,
			       Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    d_field_newGroupReq_groupName(Rest, Z1, Z2, F1, F2, F3,
				  F4, F5, F6, F7, TrUserData);
dfp_read_field_def_newGroupReq(<<16, Rest/binary>>, Z1,
			       Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    d_field_newGroupReq_groupLevel(Rest, Z1, Z2, F1, F2, F3,
				   F4, F5, F6, F7, TrUserData);
dfp_read_field_def_newGroupReq(<<26, Rest/binary>>, Z1,
			       Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    d_field_newGroupReq_note(Rest, Z1, Z2, F1, F2, F3, F4,
			     F5, F6, F7, TrUserData);
dfp_read_field_def_newGroupReq(<<34, Rest/binary>>, Z1,
			       Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    d_field_newGroupReq_remarks(Rest, Z1, Z2, F1, F2, F3,
				F4, F5, F6, F7, TrUserData);
dfp_read_field_def_newGroupReq(<<42, Rest/binary>>, Z1,
			       Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    d_field_newGroupReq_ownUser(Rest, Z1, Z2, F1, F2, F3,
				F4, F5, F6, F7, TrUserData);
dfp_read_field_def_newGroupReq(<<48, Rest/binary>>, Z1,
			       Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    d_field_newGroupReq_status(Rest, Z1, Z2, F1, F2, F3, F4,
			       F5, F6, F7, TrUserData);
dfp_read_field_def_newGroupReq(<<58, Rest/binary>>, Z1,
			       Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    d_field_newGroupReq_createDate(Rest, Z1, Z2, F1, F2, F3,
				   F4, F5, F6, F7, TrUserData);
dfp_read_field_def_newGroupReq(<<>>, 0, 0, F1, F2, F3,
			       F4, F5, F6, F7, _) ->
    #newGroupReq{groupName = F1, groupLevel = F2, note = F3,
		 remarks = F4, ownUser = F5, status = F6,
		 createDate = F7};
dfp_read_field_def_newGroupReq(Other, Z1, Z2, F1, F2,
			       F3, F4, F5, F6, F7, TrUserData) ->
    dg_read_field_def_newGroupReq(Other, Z1, Z2, F1, F2, F3,
				  F4, F5, F6, F7, TrUserData).

dg_read_field_def_newGroupReq(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_newGroupReq(Rest, N + 7,
				  X bsl N + Acc, F1, F2, F3, F4, F5, F6, F7,
				  TrUserData);
dg_read_field_def_newGroupReq(<<0:1, X:7, Rest/binary>>,
			      N, Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_newGroupReq_groupName(Rest, 0, 0, F1, F2, F3,
					F4, F5, F6, F7, TrUserData);
      16 ->
	  d_field_newGroupReq_groupLevel(Rest, 0, 0, F1, F2, F3,
					 F4, F5, F6, F7, TrUserData);
      26 ->
	  d_field_newGroupReq_note(Rest, 0, 0, F1, F2, F3, F4, F5,
				   F6, F7, TrUserData);
      34 ->
	  d_field_newGroupReq_remarks(Rest, 0, 0, F1, F2, F3, F4,
				      F5, F6, F7, TrUserData);
      42 ->
	  d_field_newGroupReq_ownUser(Rest, 0, 0, F1, F2, F3, F4,
				      F5, F6, F7, TrUserData);
      48 ->
	  d_field_newGroupReq_status(Rest, 0, 0, F1, F2, F3, F4,
				     F5, F6, F7, TrUserData);
      58 ->
	  d_field_newGroupReq_createDate(Rest, 0, 0, F1, F2, F3,
					 F4, F5, F6, F7, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_newGroupReq(Rest, 0, 0, F1, F2, F3, F4, F5,
					F6, F7, TrUserData);
	    1 ->
		skip_64_newGroupReq(Rest, 0, 0, F1, F2, F3, F4, F5, F6,
				    F7, TrUserData);
	    2 ->
		skip_length_delimited_newGroupReq(Rest, 0, 0, F1, F2,
						  F3, F4, F5, F6, F7,
						  TrUserData);
	    5 ->
		skip_32_newGroupReq(Rest, 0, 0, F1, F2, F3, F4, F5, F6,
				    F7, TrUserData)
	  end
    end;
dg_read_field_def_newGroupReq(<<>>, 0, 0, F1, F2, F3,
			      F4, F5, F6, F7, _) ->
    #newGroupReq{groupName = F1, groupLevel = F2, note = F3,
		 remarks = F4, ownUser = F5, status = F6,
		 createDate = F7}.

d_field_newGroupReq_groupName(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData)
    when N < 57 ->
    d_field_newGroupReq_groupName(Rest, N + 7,
				  X bsl N + Acc, F1, F2, F3, F4, F5, F6, F7,
				  TrUserData);
d_field_newGroupReq_groupName(<<0:1, X:7, Rest/binary>>,
			      N, Acc, _, F2, F3, F4, F5, F6, F7, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_newGroupReq(Rest2, 0, 0, NewFValue,
				   F2, F3, F4, F5, F6, F7, TrUserData).


d_field_newGroupReq_groupLevel(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData)
    when N < 57 ->
    d_field_newGroupReq_groupLevel(Rest, N + 7,
				   X bsl N + Acc, F1, F2, F3, F4, F5, F6, F7,
				   TrUserData);
d_field_newGroupReq_groupLevel(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, _, F3, F4, F5, F6, F7, TrUserData) ->
    <<NewFValue:32/signed-native>> = <<(X bsl N +
					  Acc):32/unsigned-native>>,
    dfp_read_field_def_newGroupReq(Rest, 0, 0, F1,
				   NewFValue, F3, F4, F5, F6, F7, TrUserData).


d_field_newGroupReq_note(<<1:1, X:7, Rest/binary>>, N,
			 Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData)
    when N < 57 ->
    d_field_newGroupReq_note(Rest, N + 7, X bsl N + Acc, F1,
			     F2, F3, F4, F5, F6, F7, TrUserData);
d_field_newGroupReq_note(<<0:1, X:7, Rest/binary>>, N,
			 Acc, F1, F2, _, F4, F5, F6, F7, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_newGroupReq(Rest2, 0, 0, F1, F2,
				   NewFValue, F4, F5, F6, F7, TrUserData).


d_field_newGroupReq_remarks(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData)
    when N < 57 ->
    d_field_newGroupReq_remarks(Rest, N + 7, X bsl N + Acc,
				F1, F2, F3, F4, F5, F6, F7, TrUserData);
d_field_newGroupReq_remarks(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F1, F2, F3, _, F5, F6, F7, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_newGroupReq(Rest2, 0, 0, F1, F2, F3,
				   NewFValue, F5, F6, F7, TrUserData).


d_field_newGroupReq_ownUser(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData)
    when N < 57 ->
    d_field_newGroupReq_ownUser(Rest, N + 7, X bsl N + Acc,
				F1, F2, F3, F4, F5, F6, F7, TrUserData);
d_field_newGroupReq_ownUser(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F1, F2, F3, F4, _, F6, F7, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_newGroupReq(Rest2, 0, 0, F1, F2, F3,
				   F4, NewFValue, F6, F7, TrUserData).


d_field_newGroupReq_status(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData)
    when N < 57 ->
    d_field_newGroupReq_status(Rest, N + 7, X bsl N + Acc,
			       F1, F2, F3, F4, F5, F6, F7, TrUserData);
d_field_newGroupReq_status(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F1, F2, F3, F4, F5, _, F7, TrUserData) ->
    <<NewFValue:32/signed-native>> = <<(X bsl N +
					  Acc):32/unsigned-native>>,
    dfp_read_field_def_newGroupReq(Rest, 0, 0, F1, F2, F3,
				   F4, F5, NewFValue, F7, TrUserData).


d_field_newGroupReq_createDate(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, F3, F4, F5, F6, F7, TrUserData)
    when N < 57 ->
    d_field_newGroupReq_createDate(Rest, N + 7,
				   X bsl N + Acc, F1, F2, F3, F4, F5, F6, F7,
				   TrUserData);
d_field_newGroupReq_createDate(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, F3, F4, F5, F6, _, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_newGroupReq(Rest2, 0, 0, F1, F2, F3,
				   F4, F5, F6, NewFValue, TrUserData).


skip_varint_newGroupReq(<<1:1, _:7, Rest/binary>>, Z1,
			Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    skip_varint_newGroupReq(Rest, Z1, Z2, F1, F2, F3, F4,
			    F5, F6, F7, TrUserData);
skip_varint_newGroupReq(<<0:1, _:7, Rest/binary>>, Z1,
			Z2, F1, F2, F3, F4, F5, F6, F7, TrUserData) ->
    dfp_read_field_def_newGroupReq(Rest, Z1, Z2, F1, F2, F3,
				   F4, F5, F6, F7, TrUserData).


skip_length_delimited_newGroupReq(<<1:1, X:7,
				    Rest/binary>>,
				  N, Acc, F1, F2, F3, F4, F5, F6, F7,
				  TrUserData)
    when N < 57 ->
    skip_length_delimited_newGroupReq(Rest, N + 7,
				      X bsl N + Acc, F1, F2, F3, F4, F5, F6, F7,
				      TrUserData);
skip_length_delimited_newGroupReq(<<0:1, X:7,
				    Rest/binary>>,
				  N, Acc, F1, F2, F3, F4, F5, F6, F7,
				  TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_newGroupReq(Rest2, 0, 0, F1, F2, F3,
				   F4, F5, F6, F7, TrUserData).


skip_32_newGroupReq(<<_:32, Rest/binary>>, Z1, Z2, F1,
		    F2, F3, F4, F5, F6, F7, TrUserData) ->
    dfp_read_field_def_newGroupReq(Rest, Z1, Z2, F1, F2, F3,
				   F4, F5, F6, F7, TrUserData).


skip_64_newGroupReq(<<_:64, Rest/binary>>, Z1, Z2, F1,
		    F2, F3, F4, F5, F6, F7, TrUserData) ->
    dfp_read_field_def_newGroupReq(Rest, Z1, Z2, F1, F2, F3,
				   F4, F5, F6, F7, TrUserData).






merge_msgs(Prev, New) -> merge_msgs(Prev, New, []).

merge_msgs(Prev, New, Opts)
    when element(1, Prev) =:= element(1, New) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Prev of
      #newGroupReq{} ->
	  merge_msg_newGroupReq(Prev, New, TrUserData)
    end.

merge_msg_newGroupReq(#newGroupReq{groupLevel =
				       PFgroupLevel,
				   note = PFnote, remarks = PFremarks,
				   createDate = PFcreateDate},
		      #newGroupReq{groupName = NFgroupName,
				   groupLevel = NFgroupLevel, note = NFnote,
				   remarks = NFremarks, ownUser = NFownUser,
				   status = NFstatus,
				   createDate = NFcreateDate},
		      _) ->
    #newGroupReq{groupName = NFgroupName,
		 groupLevel =
		     if NFgroupLevel =:= undefined -> PFgroupLevel;
			true -> NFgroupLevel
		     end,
		 note =
		     if NFnote =:= undefined -> PFnote;
			true -> NFnote
		     end,
		 remarks =
		     if NFremarks =:= undefined -> PFremarks;
			true -> NFremarks
		     end,
		 ownUser = NFownUser, status = NFstatus,
		 createDate =
		     if NFcreateDate =:= undefined -> PFcreateDate;
			true -> NFcreateDate
		     end}.



verify_msg(Msg) -> verify_msg(Msg, []).

verify_msg(Msg, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #newGroupReq{} ->
	  v_msg_newGroupReq(Msg, [newGroupReq], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-dialyzer({nowarn_function,v_msg_newGroupReq/3}).
v_msg_newGroupReq(#newGroupReq{groupName = F1,
			       groupLevel = F2, note = F3, remarks = F4,
			       ownUser = F5, status = F6, createDate = F7},
		  Path, _) ->
    v_type_string(F1, [groupName | Path]),
    if F2 == undefined -> ok;
       true -> v_type_int32(F2, [groupLevel | Path])
    end,
    if F3 == undefined -> ok;
       true -> v_type_string(F3, [note | Path])
    end,
    if F4 == undefined -> ok;
       true -> v_type_string(F4, [remarks | Path])
    end,
    v_type_string(F5, [ownUser | Path]),
    v_type_int32(F6, [status | Path]),
    if F7 == undefined -> ok;
       true -> v_type_string(F7, [createDate | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_type_int32/2}).
v_type_int32(N, _Path)
    when -2147483648 =< N, N =< 2147483647 ->
    ok;
v_type_int32(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, int32, signed, 32},
		  N, Path);
v_type_int32(X, Path) ->
    mk_type_error({bad_integer, int32, signed, 32}, X,
		  Path).

-dialyzer({nowarn_function,v_type_string/2}).
v_type_string(S, Path) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path) ->
    mk_type_error(bad_unicode_string, X, Path).

-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(string:join(lists:map(fun atom_to_list/1,
				       lists:reverse(PathR)),
			     ".")).



-compile({inline,id/2}).
id(X, _TrUserData) -> X.




get_msg_defs() ->
    [{{msg, newGroupReq},
      [#field{name = groupName, fnum = 1, rnum = 2,
	      type = string, occurrence = required, opts = []},
       #field{name = groupLevel, fnum = 2, rnum = 3,
	      type = int32, occurrence = optional, opts = []},
       #field{name = note, fnum = 3, rnum = 4, type = string,
	      occurrence = optional, opts = []},
       #field{name = remarks, fnum = 4, rnum = 5,
	      type = string, occurrence = optional, opts = []},
       #field{name = ownUser, fnum = 5, rnum = 6,
	      type = string, occurrence = required, opts = []},
       #field{name = status, fnum = 6, rnum = 7, type = int32,
	      occurrence = required, opts = []},
       #field{name = createDate, fnum = 7, rnum = 8,
	      type = string, occurrence = optional, opts = []}]}].


get_msg_names() -> [newGroupReq].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def(newGroupReq) ->
    [#field{name = groupName, fnum = 1, rnum = 2,
	    type = string, occurrence = required, opts = []},
     #field{name = groupLevel, fnum = 2, rnum = 3,
	    type = int32, occurrence = optional, opts = []},
     #field{name = note, fnum = 3, rnum = 4, type = string,
	    occurrence = optional, opts = []},
     #field{name = remarks, fnum = 4, rnum = 5,
	    type = string, occurrence = optional, opts = []},
     #field{name = ownUser, fnum = 5, rnum = 6,
	    type = string, occurrence = required, opts = []},
     #field{name = status, fnum = 6, rnum = 7, type = int32,
	    occurrence = required, opts = []},
     #field{name = createDate, fnum = 7, rnum = 8,
	    type = string, occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


get_package_name() -> 'com.paintfriend.chat.proto'.



gpb_version_as_string() ->
    "3.26.4".

gpb_version_as_list() ->
    [3,26,4].
