%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(registReq_pb).
-define(registReq_pb, true).

-define(registReq_pb_gpb_version, "3.26.4").

-ifndef('REGISTREQ_PB_H').
-define('REGISTREQ_PB_H', true).
-record(registReq,
        {nickname               :: binary() | iolist(), % = 1
         password               :: binary() | iolist(), % = 2
         mobile                 :: binary() | iolist() % = 3
        }).
-endif.

-endif.
