%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(releaseGroupReq_pb).
-define(releaseGroupReq_pb, true).

-define(releaseGroupReq_pb_gpb_version, "3.26.4").

-ifndef('RELEASEGROUPREQ_PB_H').
-define('RELEASEGROUPREQ_PB_H', true).
-record(releaseGroupReq,
        {id                     :: integer(),       % = 1, 32 bits
         reson                  :: binary() | iolist() | undefined % = 2
        }).
-endif.

-endif.
