%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(removeGroupMemberReq_pb).
-define(removeGroupMemberReq_pb, true).

-define(removeGroupMemberReq_pb_gpb_version, "3.26.4").

-ifndef('GROUPMEMBER_PB_H').
-define('GROUPMEMBER_PB_H', true).
-record(groupMember,
        {groupId                :: integer(),       % = 1, 32 bits
         userId                 :: binary() | iolist(), % = 2
         nickName               :: binary() | iolist() | undefined % = 3
        }).
-endif.

-ifndef('REMOVEGROUPMEMBERREQ_PB_H').
-define('REMOVEGROUPMEMBERREQ_PB_H', true).
-record(removeGroupMemberReq,
        {members = []           :: [#groupMember{}] % = 1
        }).
-endif.

-endif.
