%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(removeFriendReq_pb).
-define(removeFriendReq_pb, true).

-define(removeFriendReq_pb_gpb_version, "3.26.4").

-ifndef('REMOVEFRIENDREQ_PB_H').
-define('REMOVEFRIENDREQ_PB_H', true).
-record(removeFriendReq,
        {toUser                 :: binary() | iolist(), % = 1
         sendFrom               :: binary() | iolist() % = 2
        }).
-endif.

-endif.
