%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(respBuffer_pb).
-define(respBuffer_pb, true).

-define(respBuffer_pb_gpb_version, "3.26.4").

-ifndef('RESPBUFFER_PB_H').
-define('RESPBUFFER_PB_H', true).
-record(respBuffer,
        {result                 :: integer(),       % = 1, 32 bits
         msg                    :: binary() | iolist(), % = 2
         data                   :: binary() | iolist() | undefined % = 3
        }).
-endif.

-endif.
