%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(searchFriendReq_pb).
-define(searchFriendReq_pb, true).

-define(searchFriendReq_pb_gpb_version, "3.26.4").

-ifndef('SEARCHFRIENDREQ_PB_H').
-define('SEARCHFRIENDREQ_PB_H', true).
-record(searchFriendReq,
        {account                :: binary() | iolist(), % = 1
         mobile                 :: binary() | iolist() | undefined % = 2
        }).
-endif.

-endif.
