%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(topic_pb).
-define(topic_pb, true).

-define(topic_pb_gpb_version, "3.26.4").

-ifndef('TOPICRESPONSE_PB_H').
-define('TOPICRESPONSE_PB_H', true).
-record(topicResponse,
        {err_code               :: integer(),       % = 1, 32 bits
         err_msg                :: binary() | iolist() % = 2
        }).
-endif.

-ifndef('TOPICREQUEST_PB_H').
-define('TOPICREQUEST_PB_H', true).
-record(topicRequest,
        {topic                  :: binary() | iolist() % = 1
        }).
-endif.

-endif.
