%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(updateProfileReq_pb).
-define(updateProfileReq_pb, true).

-define(updateProfileReq_pb_gpb_version, "3.26.4").

-ifndef('UPDATEPROFILEREQ_PB_H').
-define('UPDATEPROFILEREQ_PB_H', true).
-record(updateProfileReq,
        {uid                    :: binary() | iolist(), % = 1
         nickname               :: binary() | iolist(), % = 2
         status                 :: integer(),       % = 3, 32 bits
         mobile                 :: binary() | iolist(), % = 4
         avatar                 :: binary() | iolist() | undefined, % = 5
         rolestr                :: binary() | iolist() | undefined, % = 6
         lat                    :: binary() | iolist() | undefined, % = 7
         lng                    :: binary() | iolist() | undefined % = 8
        }).
-endif.

-endif.
