%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(updateGroupReq_pb).
-define(updateGroupReq_pb, true).

-define(updateGroupReq_pb_gpb_version, "3.26.4").

-ifndef('UPDATEGROUPREQ_PB_H').
-define('UPDATEGROUPREQ_PB_H', true).
-record(updateGroupReq,
        {id                     :: integer(),       % = 1, 32 bits
         groupName              :: binary() | iolist(), % = 2
         groupLevel             :: integer() | undefined, % = 3, 32 bits
         note                   :: binary() | iolist() | undefined, % = 4
         remarks                :: binary() | iolist() | undefined, % = 5
         ownUser                :: binary() | iolist(), % = 6
         status                 :: integer(),       % = 7, 32 bits
         createDate             :: binary() | iolist() | undefined % = 8
        }).
-endif.

-endif.
